apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qaj2nrys6-python
  janus-idp.io/tekton: qaj2nrys6-python
  backstage.io/kubernetes-id: qaj2nrys6-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qaj2nrys6-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
